MERGE Ods.`OracleEbs-GL_LEGAL_ENTITIES_BSVS` AS T using OdsStage.`OracleEbs-GL_LEGAL_ENTITIES_BSVS` AS S on T.LEGAL_ENTITY_ID = S.LEGAL_ENTITY_ID and T.FLEX_VALUE_SET_ID = S.FLEX_VALUE_SET_ID and T.FLEX_SEGMENT_VALUE = S.FLEX_SEGMENT_VALUE
WHEN MATCHED THEN
Update SET 
T.LEGAL_ENTITY_ID=S.LEGAL_ENTITY_ID
,T.FLEX_VALUE_SET_ID=S.FLEX_VALUE_SET_ID
,T.FLEX_SEGMENT_VALUE=S.FLEX_SEGMENT_VALUE
,T.START_DATE=S.START_DATE
,T.END_DATE=S.END_DATE
,T.LAST_UPDATE_DATE=S.LAST_UPDATE_DATE
,T.LAST_UPDATED_BY=S.LAST_UPDATED_BY
,T.LAST_UPDATE_LOGIN=S.LAST_UPDATE_LOGIN
,T.CREATION_DATE=S.CREATION_DATE
,T.CREATED_BY=S.CREATED_BY
,T.LoadBy = 'airflow-worker'
,T.LoadDate = CURRENT_TIMESTAMP
,T.LoadProcess = 'Dag - Corp_OracleEbs_BigQuery_GL_LEGAL_ENTITIES_BSVS_Import'
,T.UpdateBy = 'airflow-worker'
,T.UpdateDate = CURRENT_TIMESTAMP
,T.UpdateProcess = 'Dag - Corp_OracleEbs_BigQuery_GL_LEGAL_ENTITIES_BSVS_Import'
,T.InactiveInd = False
,T.InactiveReason = ''

	WHEN NOT MATCHED THEN
INSERT (ParentSystemId,SystemId,LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID, FLEX_SEGMENT_VALUE, START_DATE, END_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, CREATION_DATE, CREATED_BY, LoadBy, LoadDate, LoadProcess,CreateBy, CreateDate, CreateProcess,UpdateBy,UpdateDate,UpdateProcess,InactiveInd,InactiveReason)
VALUES (76,2578,LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID, FLEX_SEGMENT_VALUE, START_DATE, END_DATE, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, CREATION_DATE, CREATED_BY,'airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_XLE_ENTITY_PROFILES_Import','airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_XLE_ENTITY_PROFILES_Import','airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_XLE_ENTITY_PROFILES_Import',False,'')