MERGE Ods.`OracleEbs-AP_TERMS_LINES` AS T using OdsStage.`OracleEbs-AP_TERMS_LINES` AS S on T.TERM_ID = S.TERM_ID and T.SEQUENCE_NUM = S.SEQUENCE_NUM
WHEN MATCHED THEN
Update SET
T.ParentSystemId = 76
,T.SystemId = 2578		 
,T.TERM_ID	=	S.TERM_ID
,T.SEQUENCE_NUM	=	S.SEQUENCE_NUM
,T.LAST_UPDATE_DATE	=	S.LAST_UPDATE_DATE
,T.LAST_UPDATED_BY	=	S.LAST_UPDATED_BY
,T.CREATION_DATE	=	S.CREATION_DATE
,T.CREATED_BY	=	S.CREATED_BY
,T.LAST_UPDATE_LOGIN	=	S.LAST_UPDATE_LOGIN
,T.DUE_PERCENT	=	S.DUE_PERCENT
,T.DUE_AMOUNT	=	S.DUE_AMOUNT
,T.DUE_DAYS	=	S.DUE_DAYS
,T.DUE_DAY_OF_MONTH	=	S.DUE_DAY_OF_MONTH
,T.DUE_MONTHS_FORWARD	=	S.DUE_MONTHS_FORWARD
,T.DISCOUNT_PERCENT	=	S.DISCOUNT_PERCENT
,T.DISCOUNT_DAYS	=	S.DISCOUNT_DAYS
,T.DISCOUNT_DAY_OF_MONTH	=	S.DISCOUNT_DAY_OF_MONTH
,T.DISCOUNT_MONTHS_FORWARD	=	S.DISCOUNT_MONTHS_FORWARD
,T.DISCOUNT_PERCENT_2	=	S.DISCOUNT_PERCENT_2
,T.DISCOUNT_DAYS_2	=	S.DISCOUNT_DAYS_2
,T.DISCOUNT_DAY_OF_MONTH_2	=	S.DISCOUNT_DAY_OF_MONTH_2
,T.DISCOUNT_MONTHS_FORWARD_2	=	S.DISCOUNT_MONTHS_FORWARD_2
,T.DISCOUNT_PERCENT_3	=	S.DISCOUNT_PERCENT_3
,T.DISCOUNT_DAYS_3	=	S.DISCOUNT_DAYS_3
,T.DISCOUNT_DAY_OF_MONTH_3	=	S.DISCOUNT_DAY_OF_MONTH_3
,T.DISCOUNT_MONTHS_FORWARD_3	=	S.DISCOUNT_MONTHS_FORWARD_3
,T.ATTRIBUTE_CATEGORY	=	S.ATTRIBUTE_CATEGORY
,T.ATTRIBUTE1	=	S.ATTRIBUTE1
,T.ATTRIBUTE2	=	S.ATTRIBUTE2
,T.ATTRIBUTE3	=	S.ATTRIBUTE3
,T.ATTRIBUTE4	=	S.ATTRIBUTE4
,T.ATTRIBUTE5	=	S.ATTRIBUTE5
,T.ATTRIBUTE6	=	S.ATTRIBUTE6
,T.ATTRIBUTE7	=	S.ATTRIBUTE7
,T.ATTRIBUTE8	=	S.ATTRIBUTE8
,T.ATTRIBUTE9	=	S.ATTRIBUTE9
,T.ATTRIBUTE10	=	S.ATTRIBUTE10
,T.ATTRIBUTE11	=	S.ATTRIBUTE11
,T.ATTRIBUTE12	=	S.ATTRIBUTE12
,T.ATTRIBUTE13	=	S.ATTRIBUTE13
,T.ATTRIBUTE14	=	S.ATTRIBUTE14
,T.ATTRIBUTE15	=	S.ATTRIBUTE15
,T.FIXED_DATE	=	S.FIXED_DATE
,T.CALENDAR	=	S.CALENDAR
,T.DISCOUNT_AMOUNT	=	S.DISCOUNT_AMOUNT
,T.DISCOUNT_CRITERIA	=	S.DISCOUNT_CRITERIA
,T.DISCOUNT_AMOUNT_2	=	S.DISCOUNT_AMOUNT_2
,T.DISCOUNT_CRITERIA_2	=	S.DISCOUNT_CRITERIA_2
,T.DISCOUNT_AMOUNT_3	=	S.DISCOUNT_AMOUNT_3
,T.DISCOUNT_CRITERIA_3	=	S.DISCOUNT_CRITERIA_3 
,T.LoadBy = 'airflow-worker'
,T.LoadDate = CURRENT_TIMESTAMP
,T.LoadProcess = 'Dag - Corp_OracleEbs_BigQuery_AP_TERMS_LINES_Import'
,T.CreateBy = 'airflow-worker'
,T.CreateDate = CURRENT_TIMESTAMP
,T.CreateProcess = 'Dag - Corp_OracleEbs_BigQuery_AP_TERMS_LINES_Import'
,T.UpdateBy = 'airflow-worker'
,T.UpdateDate = CURRENT_TIMESTAMP
,T.UpdateProcess = 'Dag - Corp_OracleEbs_BigQuery_AP_TERMS_LINES_Import'
,T.InactiveInd = False
,T.InactiveReason = ''

	WHEN NOT MATCHED THEN
INSERT (ParentSystemId,SystemId,TERM_ID,	SEQUENCE_NUM,	LAST_UPDATE_DATE,	LAST_UPDATED_BY,	CREATION_DATE,	CREATED_BY,	LAST_UPDATE_LOGIN,	DUE_PERCENT,	DUE_AMOUNT,	DUE_DAYS,	DUE_DAY_OF_MONTH,	DUE_MONTHS_FORWARD,	DISCOUNT_PERCENT,	DISCOUNT_DAYS,	DISCOUNT_DAY_OF_MONTH,	DISCOUNT_MONTHS_FORWARD,	DISCOUNT_PERCENT_2,	DISCOUNT_DAYS_2,	DISCOUNT_DAY_OF_MONTH_2,	DISCOUNT_MONTHS_FORWARD_2,	DISCOUNT_PERCENT_3,	DISCOUNT_DAYS_3,	DISCOUNT_DAY_OF_MONTH_3,	DISCOUNT_MONTHS_FORWARD_3,	ATTRIBUTE_CATEGORY,	ATTRIBUTE1,	ATTRIBUTE2,	ATTRIBUTE3,	ATTRIBUTE4,	ATTRIBUTE5,	ATTRIBUTE6,	ATTRIBUTE7,	ATTRIBUTE8,	ATTRIBUTE9,	ATTRIBUTE10,	ATTRIBUTE11,	ATTRIBUTE12,	ATTRIBUTE13,	ATTRIBUTE14,	ATTRIBUTE15,	FIXED_DATE,	CALENDAR,	DISCOUNT_AMOUNT,	DISCOUNT_CRITERIA,	DISCOUNT_AMOUNT_2,	DISCOUNT_CRITERIA_2,	DISCOUNT_AMOUNT_3,	DISCOUNT_CRITERIA_3,LoadBy, LoadDate, LoadProcess,CreateBy, CreateDate, CreateProcess,UpdateBy,UpdateDate,UpdateProcess,InactiveInd,InactiveReason)
VALUES (76,2578,TERM_ID,	SEQUENCE_NUM,	LAST_UPDATE_DATE,	LAST_UPDATED_BY,	CREATION_DATE,	CREATED_BY,	LAST_UPDATE_LOGIN,	DUE_PERCENT,	DUE_AMOUNT,	DUE_DAYS,	DUE_DAY_OF_MONTH,	DUE_MONTHS_FORWARD,	DISCOUNT_PERCENT,	DISCOUNT_DAYS,	DISCOUNT_DAY_OF_MONTH,	DISCOUNT_MONTHS_FORWARD,	DISCOUNT_PERCENT_2,	DISCOUNT_DAYS_2,	DISCOUNT_DAY_OF_MONTH_2,	DISCOUNT_MONTHS_FORWARD_2,	DISCOUNT_PERCENT_3,	DISCOUNT_DAYS_3,	DISCOUNT_DAY_OF_MONTH_3,	DISCOUNT_MONTHS_FORWARD_3,	ATTRIBUTE_CATEGORY,	ATTRIBUTE1,	ATTRIBUTE2,	ATTRIBUTE3,	ATTRIBUTE4,	ATTRIBUTE5,	ATTRIBUTE6,	ATTRIBUTE7,	ATTRIBUTE8,	ATTRIBUTE9,	ATTRIBUTE10,	ATTRIBUTE11,	ATTRIBUTE12,	ATTRIBUTE13,	ATTRIBUTE14,	ATTRIBUTE15,	FIXED_DATE,	CALENDAR,	DISCOUNT_AMOUNT,	DISCOUNT_CRITERIA,	DISCOUNT_AMOUNT_2,	DISCOUNT_CRITERIA_2,	DISCOUNT_AMOUNT_3,	DISCOUNT_CRITERIA_3,'airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_AP_TERMS_LINES_Import','airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_AP_TERMS_LINES_Import','airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_AP_TERMS_LINES_Import',False,'')