MERGE DevEmployeeOds.`OracleEbs-AP_HOLD_CODES` AS T using DevEmployeeOdsStage.`OracleEbs-AP_HOLD_CODES` AS S on T.HOLD_LOOKUP_CODE = S.HOLD_LOOKUP_CODE
WHEN MATCHED THEN
Update SET
T.ParentSystemId = 76
,T.SystemId = 2578		 
,T.HOLD_LOOKUP_CODE	=	S.HOLD_LOOKUP_CODE
,T.HOLD_TYPE	=	S.HOLD_TYPE
,T.DESCRIPTION	=	S.DESCRIPTION
,T.LAST_UPDATE_DATE	=	S.LAST_UPDATE_DATE
,T.LAST_UPDATED_BY	=	S.LAST_UPDATED_BY
,T.USER_RELEASEABLE_FLAG	=	S.USER_RELEASEABLE_FLAG
,T.USER_UPDATEABLE_FLAG	=	S.USER_UPDATEABLE_FLAG
,T.INACTIVE_DATE	=	S.INACTIVE_DATE
,T.POSTABLE_FLAG	=	S.POSTABLE_FLAG
,T.LAST_UPDATE_LOGIN	=	S.LAST_UPDATE_LOGIN
,T.CREATION_DATE	=	S.CREATION_DATE
,T.CREATED_BY	=	S.CREATED_BY
,T.EXTERNAL_DESCRIPTION	=	S.EXTERNAL_DESCRIPTION
,T.HOLD_INSTRUCTION	=	S.HOLD_INSTRUCTION
,T.WAIT_BEFORE_NOTIFY_DAYS	=	S.WAIT_BEFORE_NOTIFY_DAYS
,T.REMINDER_DAYS	=	S.REMINDER_DAYS
,T.INITIATE_WORKFLOW_FLAG	=	S.INITIATE_WORKFLOW_FLAG
,T.LoadBy = 'airflow-worker'
,T.LoadDate = CURRENT_TIMESTAMP
,T.LoadProcess = 'Dag - Corp_OracleEbs_BigQuery_AP_HOLD_CODES_Import'
,T.CreateBy = 'airflow-worker'
,T.CreateDate = CURRENT_TIMESTAMP
,T.CreateProcess = 'Dag - Corp_OracleEbs_BigQuery_AP_HOLD_CODES_Import'
,T.UpdateBy = 'airflow-worker'
,T.UpdateDate = CURRENT_TIMESTAMP
,T.UpdateProcess = 'Dag - Corp_OracleEbs_BigQuery_AP_HOLD_CODES_Import'
,T.InactiveInd = False
,T.InactiveReason = ''

	WHEN NOT MATCHED THEN
INSERT (ParentSystemId,SystemId,HOLD_LOOKUP_CODE, HOLD_TYPE, DESCRIPTION, LAST_UPDATE_DATE, LAST_UPDATED_BY, USER_RELEASEABLE_FLAG, USER_UPDATEABLE_FLAG, INACTIVE_DATE, POSTABLE_FLAG, LAST_UPDATE_LOGIN, CREATION_DATE, CREATED_BY, EXTERNAL_DESCRIPTION, HOLD_INSTRUCTION, WAIT_BEFORE_NOTIFY_DAYS, REMINDER_DAYS, INITIATE_WORKFLOW_FLAG, LoadBy, LoadDate, LoadProcess,CreateBy, CreateDate, CreateProcess,UpdateBy,UpdateDate,UpdateProcess,InactiveInd,InactiveReason)
VALUES (76,2578,HOLD_LOOKUP_CODE, HOLD_TYPE, DESCRIPTION, LAST_UPDATE_DATE, LAST_UPDATED_BY, USER_RELEASEABLE_FLAG, USER_UPDATEABLE_FLAG, INACTIVE_DATE, POSTABLE_FLAG, LAST_UPDATE_LOGIN, CREATION_DATE, CREATED_BY, EXTERNAL_DESCRIPTION, HOLD_INSTRUCTION, WAIT_BEFORE_NOTIFY_DAYS, REMINDER_DAYS, INITIATE_WORKFLOW_FLAG,'airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_AP_HOLD_CODES_Import','airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_AP_HOLD_CODES_Import','airflow-worker',CURRENT_TIMESTAMP,'Dag - Corp_OracleEbs_BigQuery_AP_HOLD_CODES_Import',False,'')